spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/gdsc
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #?? ??? Create?? ??? ?. (??: ?? ??? ???? ???.)
