my:
  auth:
    key1: Krs6ISTonkcqG6OlMztbDPTKLGN%2B666qfnEeYkXMzX%2BqGUyvILTA9IM1BNgD%2F%2BTRXpzlCFIkWGKrKFPo2qwtQQ%3D%3D
    key2: Krs6ISTonkcqG6OlMztbDPTKLGN+666qfnEeYkXMzX+qGUyvILTA9IM1BNgD/+TRXpzlCFIkWGKrKFPo2qwtQQ==

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hackathon2023/hack
    username: sa
    password:
      driver-class-name: org.h2.Driver
  mvc:
    view:
      prefix:
      suffix: .html

  jpa:
    hibernate:
      ddl-auto: create # table 자동 생성
    #      ddl-auto: none # db 초기화 없앰
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
server:
  port: 8080
  servlet:
    session:
      timeout: 30m # session timeout 30min

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace